(define-public (revoke-milestone (campaign-id uint) (milestone-id uint))
  (let ((milestone (unwrap! (map-get? milestones { campaign-id: campaign-id, milestone-id: milestone-id }) ERR_MILESTONE_NOT_FOUND)))
    (asserts! (is-eq tx-sender contract-owner) ERR_NOT_AUTHORIZED)
    (ok (map-set milestones { campaign-id: campaign-id, milestone-id: milestone-id } (merge milestone { status: "REVOKED", completed: false })))
  )
)
